### PR TITLE
chore(axiom-materials): add rgb variable for all colors

### PR DESCRIPTION
**Pull request by eliotstocker**
they can now be used to construct an RGBA with opacity variables

### CODE REVIEW

**Comment by lpoulter** [comment]
Hi Elliot thanks for the PR. Are you able to provide an example use case to help my understanding?

**Comment by eliotstocker** [comment]
Hey Laurie,

im currently working on slipstream UI, which previously was using hard coded copies of the axiom colors, there is a number of CSS animations etc where we require using axiom colors with a set opacity for a color.

Example:
```
@keyframes stageProgress {
  0% {
    box-shadow: 0 0 0 0 rgba(var(--rgb-product-paradise-lost), var(--opacity-input-border--focused));
  }
  70% {
    box-shadow: 0 0 5px 10px rgba(var(--rgb-product-paradise-lost), 0);
  }
  100% {
    box-shadow: 0 0 0 0 rgba(var(--rgb-product-paradise-lost), 0);
  }
}
```

this way if i just need the color i can use var(--color-product-paradise-lost),
but if i need the color with a set opacity i can then do something like: `rgba(var(--rgb-product-paradise-lost), var(--opacity-input-border--focused));`

**Comment by lpoulter** [comment]
Ok good stuff that makes sense to me. 
We are unpacking
`--color-product-tiny-clanger: rgb(var(--rgb-product-tiny-clanger));`  
to 
```
--rgb-product-tiny-clanger: 244, 152, 183;
--color-product-tiny-clanger: rgb(var(--rgb-product-tiny-clanger));
```

**Comment by lpoulter** [comment]
Looks like your build is failing due to our commit message lint rules. You can run `yarn lint:commits` to debug locally.

**Comment by eliotstocker** [comment]
all seems to be passing locally :(

**Pull request merged**
