### PR TITLE
fix(axiom-components): fix horizontalPadding in TableCell

### PR DESCRIPTION
**Pull request by tomru**
While experimenting with nesting tables I've stumbled over an issue when trying to set `horizontalPadding="none"` to a table cell, that did not work as expected.

See this [sandbox](https://codesandbox.io/s/axiom-tablecell-horizontalpadding-none-bug-sc5n0). This PR fixes the wrong usage of css properties for both the `none` case and `medium` case (which is the default anyways).

### CODE REVIEW

**Review by jdelight — APPROVED** [review]
Thanks @tomru - surprised this wasn't noticed before - although there are probably missing tests around this.

**Comment by tomru** [comment]
> although there are probably missing tests around this.

the existing tests would not have helped here, as they just check if the right css class is set :fried_shrimp:

**Comment by tomru** [comment]
@BrandwatchLtd/axiom can I please have a 2nd review on this one?

**Review by josa42 — APPROVED** [review]

**Comment by lpoulter** [comment]
Thanks for the fix.

**Pull request merged**
