### PR TITLE
chore(React): Make use of react versions consistent 

### PR DESCRIPTION
**Pull request by lpoulter**
We are using two versions of React. 1 > 2.

### CODE REVIEW

**Comment by lpoulter** [comment]
> Fine by me but will it cause issues for anyone on older versions of React?

Hmm I'm not certain but if you where on an older version of React wouldn't that get installed along side 16.8.6?

**Comment by larister** [comment]
Yeah that's what I'm worried about considering we've had bugs with different React versions being installed alongside each other....

When you say "We are already 16.8.6 elsewhere", does that mean all the other apps consuming Axiom? Or just Audiences?

**Comment by lpoulter** [comment]
I mean other axiom packages are already using 16.8.

**Comment by lpoulter** [comment]
@larister. I've done some testing with project with older versions and can't see any problems. I'm gonna merge this as I think it will fix the issues I'm seeing in audiences.

**Pull request merged**
